defaults:
  - base_dataset
  - view_sampler: all

name: nuscenes
roots: [datasets/nuscenes/processed_10Hz/trainval2]
split_file_path: nuScenes_Train.txt
numTimes: 1  # total number of timesteps in each scene

input_image_shape: [252, 448] # not used here
original_image_shape: [900, 1600] # 252x448
cameras_are_circular: false

# 基线缩放相关，
baseline_min: 1e-3 # 
baseline_max: 1e2 # 
max_fov: 180.0
avg_pose: false # not used here

# not used here
rescale_to_1cube: false # not used here
make_baseline_1: false
intr_augment: false # 缩放增强，not used here